### ISSUE TITLE
builder.finalize generates all zeroes

### ISSUE THREAD

**Issue by asquelt** [yitsushi/midea-air-condition#3]
i don't know if it's just me or ruby version, but i'm getting (i've just added printing args and results in send_api_request to your example code from readme):
```
# ./midea.rb 
{"appId":1017,"format":2,"clientType":1,"language":"en_US","src":17,"stamp":"20180828180446","loginAccount":"ceop+...@kondi.net","sign":"xxx"}
{"msg":"","result":{"loginId":"416aab29-3160-4ea9-a478-2684d6802c8e"},"errorCode":"0"}
{"loginId"=>"416aab29-3160-4ea9-a478-2684d6802c8e"}
{"appId":1017,"format":2,"clientType":1,"language":"en_US","src":17,"stamp":"20180828180447","loginAccount":"ceop+...@kondi.net","password":"xxx","sign":"xxx"}
{"msg":"","result":{"originPrivateVersion":"","nickname":"ceop+...@kondi.net","sessionId":"xxx","accessToken":"xxx","userId":"703005","versionCode":"","leftCount":""},"errorCode":"0"}
{"originPrivateVersion"=>"", "nickname"=>"ceop+...@kondi.net", "sessionId"=>"xxx", "accessToken"=>"xxx", "userId"=>"703005", "versionCode"=>"", "leftCount"=>""}
{"appId":1017,"format":2,"clientType":1,"language":"en_US","src":17,"stamp":"20180828180448","sessionId":"xxx","sign":"xxx"}
{"msg":"","result":{"list":[{"number":"703005","isDefault":"1","createUserId":"703005","des":"","address":"","coordinate":"","createTime":"2018-08-27 17:56:59","roleId":"1001","name":"","nickname":"","id":"703005"}]},"errorCode":"0"}
{"list"=>[{"number"=>"703005", "isDefault"=>"1", "createUserId"=>"703005", "des"=>"", "address"=>"", "coordinate"=>"", "createTime"=>"2018-08-27 17:56:59", "roleId"=>"1001", "name"=>"", "nickname"=>"", "id"=>"703005"}]}
{"appId":1017,"format":2,"clientType":1,"language":"en_US","src":17,"stamp":"20180828180450","homegroupId":"703005","sessionId":"xxx","sign":"xxx"}
{"msg":"","result":{"list":[{"des":"","activeStatus":"1","onlineStatus":"1","name":"Kondycjoner","modelNumber":"0","id":"17592186059380","sn":"4438b04aa5eb780f2fafb2e2eba48474ec4eb27af92cfe4d580953370fb8a137fa04a2251c9b08b7f85672154b3391be","type":"0xAC"}]},"errorCode":"0"}
{"list"=>[{"des"=>"", "activeStatus"=>"1", "onlineStatus"=>"1", "name"=>"Kondycjoner", "modelNumber"=>"0", "id"=>"17592186059380", "sn"=>"4438b04aa5eb780f2fafb2e2eba48474ec4eb27af92cfe4d580953370fb8a137fa04a2251c9b08b7f85672154b3391be", "type"=>"0xAC"}]}
[id=17592186059380 type=0xAC] Kondycjoner is online and active.
{"appId":1017,"format":2,"clientType":1,"language":"en_US","src":17,"stamp":"20180828180450","order":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","funId":"0000","applianceId":"17592186059380","sessionId":"xxx","sign":"xxx"}
{"msg":"system error","errorCode":"9999"}
/root/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/midea-air-condition-0.0.2/lib/client.rb:103:in `block in send_api_request': system error (RuntimeError)
	from /root/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/http.rb:877:in `start'
	from /root/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/http.rb:608:in `start'
	from /root/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/midea-air-condition-0.0.2/lib/client.rb:96:in `send_api_request'
	from /root/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/midea-air-condition-0.0.2/lib/client.rb:90:in `api_request'
	from /root/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/midea-air-condition-0.0.2/lib/client.rb:52:in `appliance_transparent_send'
	from ./midea.rb:33:in `<main>'
```
```ruby 2.4.0p0 (2016-12-24 revision 57164) [armv7l-linux-eabihf]``` running on ```Raspbian GNU/Linux 9.4 (stretch)```

**Comment by asquelt** [comment]
i've installed ```ruby 2.5.1p57 (2018-03-29 revision 63029) [armv7l-linux-eabihf]``` and it works just fine. so it might be worth a note that gem ruby version requirement should be 2.5.1 (2.5.0?) not 2.4.0.

**Comment by yitsushi** [comment]
Sorry, did not notice this notification :(

I will dig in a bit deeper what's in there. I think I remember something similar, but later I could not reproduce it. Our is running on Raspbian too. As I know (can't check now), we use ruby 2.4 too.

**Comment by yitsushi** [comment]
As I checked now, we are using `2.4.1` (`ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]`) on our target machine. I tried to reproduce the same error in docker and with `2.4.0` I got it. The problem is the `unpack1` on call in my aes functions. Somehow it returns zeros. I don't know why yet.

**Comment by yitsushi** [comment]
```
irb(main):003:0> "asdf".unpack1('H*')
=> "\x00\x00\x00\x00\x00\x00\x00\x00"
```

**Comment by yitsushi** [comment]
With the `0.0.3` it works. Thanks for the feedback.

```
root@0a578634d8e9:/# gem list | grep midea
midea-air-condition (0.0.3)
root@0a578634d8e9:/# ruby --version
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
root@0a578634d8e9:/# midea-ac get 18691697682595
Device is turned off.
Target temperature: 22 celsius
Indoor temperature: 24 celsius
Outdoor temperature: 22 celsius
Mode: cool
Fan speed: 40
TimerOn is not active.
TimerOff is not active.
Eco mode is off.
```

**Comment by cyberfly79** [comment]
I've tried it in 2.4.0, 2.4.4, 2.5.1, and I get the same error in each. Sometimes it is executed without error.

How long should it take between commands? How often can I get a query from Home-Assistant?



/usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/midea-air-condition-0.0.3/lib/client.rb:101:in `block in send_api_request': The asyn reply does not exist  (RuntimeError)
        from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:877:in `start'
        from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/http.rb:608:in `start'
        from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/midea-air-condition-0.0.3/lib/client.rb:96:in `send_api_request'
        from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/midea-air-condition-0.0.3/lib/client.rb:90:in `api_request'
        from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/midea-air-condition-0.0.3/lib/client.rb:52:in `appliance_transparent_send'
        from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/midea-air-condition-0.0.3/bin/midea-ac:117:in `send_command'
        from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/midea-air-condition-0.0.3/bin/midea-ac:41:in `get'
        from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/midea-air-condition-0.0.3/bin/midea-ac:167:in `<top (required)>'
        from midea-ac:23:in `load'
        from midea-ac:23:in `<main>'


/usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/midea-air-condition-0.0.3/lib/client.rb:101:in `block in send_api_request': The asyn reply does not exist  (RuntimeError)
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/net/http.rb:877:in `start'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/2.4.0/net/http.rb:608:in `start'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/midea-air-condition-0.0.3/lib/client.rb:96:in `send_api_request'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/midea-air-condition-0.0.3/lib/client.rb:90:in `api_request'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/midea-air-condition-0.0.3/lib/client.rb:52:in `appliance_transparent_send'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/midea-air-condition-0.0.3/bin/midea-ac:117:in `send_command'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/midea-air-condition-0.0.3/bin/midea-ac:41:in `get'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from /usr/local/rvm/rubies/ruby-2.4.4/lib/ruby/gems/2.4.0/gems/midea-air-condition-0.0.3/bin/midea-ac:167:in `<top (required)>'
        from midea-ac:23:in `load'
        from midea-ac:23:in `<main>'


Traceback (most recent call last):
        14: from midea-ac:23:in `<main>'
        13: from midea-ac:23:in `load'
        12: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/midea-air-condition-0.0.3/bin/midea-ac:187:in `<top (required)>'
        11: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        10: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
         9: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
         8: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
         7: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/midea-air-condition-0.0.3/bin/midea-ac:41:in `get'
         6: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/midea-air-condition-0.0.3/bin/midea-ac:137:in `send_command'
         5: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/midea-air-condition-0.0.3/lib/client.rb:52:in `appliance_transparent_send'
         4: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/midea-air-condition-0.0.3/lib/client.rb:90:in `api_request'
         3: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/midea-air-condition-0.0.3/lib/client.rb:96:in `send_api_request'
         2: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:609:in `start'
         1: from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:910:in `start'
/usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/midea-air-condition-0.0.3/lib/client.rb:101:in `block in send_api_request': The asyn reply does not exist  (RuntimeError)

**Comment by yitsushi** [comment]
@cyberfly79 : I think it's a different issue. I saw asyn reply errors when I tried to send a lot of commands in a short period (like 10 in a second) and it was not enough to propagate back to our AC from their server and in a result the AC device got 3-4 commands at the same time and could not able to follow what's happening so it just gave up. Or something similar. I don't know Home Assistant at all, so I can't help with that.
